### ISSUE TITLE
the official windows distribution is unsigned.

### ISSUE THREAD

**Issue by mikaelosterberg** [Nitrokey/nitrokey-app#136] opened 2016-09-12 07:27 UTC
The app downloaded from https://www.nitrokey.com/download aren't signed. 
Even if i role my one exe it wood be nice to have a official signed file that i know have not been tempered with after the developer have compiled it.

**Comment by szszszsz** [comment] 2016-09-19 09:16
Closing as a duplicate of #110 . In case of any additional suggestions please reply there. Thank you!

**Closed by szszszsz** 2016-09-19 09:16 UTC
