### ISSUE TITLE
macOS 10.12.5 - pin dialog / Dialogbox with no focus

### ISSUE THREAD

**Issue by Peacekeeper2000** [Nitrokey/nitrokey-app#247] opened 2017-05-18 09:46 UTC
Normally when a dialog box pop's up , the box has the focus and you could just type right away. This is under macOS 10.12.5 not the case , when you want to open the encrypted volume. You first need to click into the box, before you could type. Not a big issue, but all other boxes have the focus right from the beginning

**Comment by Peacekeeper2000** [comment] 2017-05-18 18:55
One additional Observation: When you first open the About - Box , the dialog has it's focus. So it just has no focus, when it is the first thing you do in the tray application.

**Comment by jonathancross** [comment] 2017-08-10 01:16
Same issue in MacOS 10.11.6

**Comment by szszszsz** [comment] 2017-09-21 08:22
Please retest with latest version: [v1.2-beta.2](https://github.com/Nitrokey/nitrokey-app/releases/tag/v1.2-beta.2).

**Comment by jonathancross** [comment] 2017-09-23 01:24
I am seeing strange behavior in v1.2... sometimes it brings the PIN entry dialog into focus, in which cases it correctly selects the input field.  But, in many other cases, the dialog doesn't appear at all.  Neither does "About Nitrokey".  This is pretty consistent when using Chrome for example whereas Terminal works.

Once I finally get a dialog to appear (eg when using Terminal), then all the "missing dialogs" will then be shown as I click cancel.  I can also just repeatedly click "Unlock password safe" to get multiple PIN entry dialogs... may or may not be related:
![v1 2-pin-entry-dialogs](https://user-images.githubusercontent.com/5115470/30768843-918333f2-a00e-11e7-92ba-bd07788a9b19.png)

**Comment by szszszsz** [comment] 2017-09-25 11:07
Thank you for testing! I see. I will look further into that.
I will make sure too the PIN dialog will be single.

**Comment by Peacekeeper2000** [comment] 2017-09-25 12:14
In addition: I have crashes, when I try to unlock the encrypted partition: It starts blinking ( in a form of light green / yellow with some red pulses in-between) and then stucks with a "dark green". When I open the Finder Windows I can see activities and after a while it crashes - but this is not every time the case. So no improvement for this bug.

**Comment by jans23** [comment] 2017-09-25 12:20
You might have mentioned this before but just to be sure: Do you have the latest firmware 0.48 installed?

**Comment by Peacekeeper2000** [comment] 2017-09-25 12:27
Hi, no - reason was that NK Storage only worked with 0.45 . 0.46++ have not worked on MacOS.
I agree, the crashes might be depending on these firmware upgrades.
(But the dialog still has no focus :D )

**Comment by szszszsz** [comment] 2017-09-25 12:46
@Peacekeeper2000 the workarounds for Storage v0.45 have been removed during the communication clean up. Because of that unlocking Encrypted/Hidden volumes usually will not work. They are planned to be activated for v0.45 and lower versions in next beta release.

**Comment by szszszsz** [comment] 2017-10-21 05:40
Closed by merging previous (not fully working solution) to master. Reopening until confirmed it is fixed by feedback.

**Comment by Ashaman-** [comment] 2017-12-26 15:31
OSX 10.13.2 also affected

**Comment by szszszsz** [comment] 2018-01-04 10:49
Hi @Ashaman- !
Have you perhaps retested this issue on v1.2?

**Comment by szszszsz** [comment] 2018-04-09 15:10
It should work this time. Please reopen otherwise.

**Closed** 2018-04-09 15:10 UTC
Labels: UI, bug, in progress, prio:medium
