### ISSUE TITLE
[osx] Connected / Disconnected messages until segfault

### ISSUE THREAD

**Issue by jonathancross** [Nitrokey/nitrokey-app#261] opened 2017-08-10 01:56 UTC
- Application version: v1.1
- Operating system: OSX 10.11.6 (15G1611)
- Device model and firmware version: Pro / 0.8
- Connected USB port type: 3.0
- Issue occurrency: Always when I try to use with KeepassX

### Expected behaviour

Consistent messages about device being connected.

### Current behaviour

If I have keepassx open and am trying to use the Nitrokey password manager, I begin getting repeated notifications that the device is connected, then disconnected.  Eventually mac just starts counting messages and eventually app seems to crash.
![nitrokey-disconnected](https://user-images.githubusercontent.com/5115470/29150755-ef920414-7d7c-11e7-8589-14e5532dd825.png)

Also got this while trying to determine steps below:

![nitrokey-pw-error](https://user-images.githubusercontent.com/5115470/29150849-8ca5c128-7d7d-11e7-9e9b-e2d04ef4ffde.png)

#### Preconditions
Same behavior if Nitrokey is plugged into either USB port.
I get many different kinds of errors.

#### Steps
1. Plug in Nitrokey.
2. Open KeepassX
3. Click on Nitrokey app and select password.
4. Switch back to Keepassx
5. Paste.

Bizarre behavior then begins an usually the app crashes after 200-300 notifications.

### Logs

Shell output:

```
nitrokey-app --df debug-file.txt --dl 3
Qt has caught an exception thrown from an event handler. Throwing
exceptions from an event handler is not supported in Qt. You must
reimplement QApplication::notify() and catch all exceptions there.

Segmentation fault: 11
```

Logs attached:

[debug-file.txt](https://github.com/Nitrokey/nitrokey-app/files/1213418/debug-file.txt)

**Comment by szszszsz** [comment] 2017-08-16 17:40
Hi @jonathancross !
Could you reupload the logs? The file is inaccessible for some reason.
It looks like this could be caused by `Secure Input Entry` macOS feature. [Details](https://support.nitrokey.com/t/macos-sierra-and-nk-storage-connect-disconnect-depend-on-focus/234/13?u=szszszsz)

**Comment by jonathancross** [comment] 2017-08-18 18:15
Hi @szszszsz, do you mean you clicked the "debug-file.txt" link above and it does not download?
I just tried again and it works fine, here is the url: https://github.com/Nitrokey/nitrokey-app/files/1213418/debug-file.txt

Thanks for the tip about `Secure Input Entry`, unfortunatly I don't see an option for this in KeepassX app.

**Comment by szszszsz** [comment] 2017-08-19 09:32
It was actually some network error on my side - I have downloaded the logs successfully now. 
My guess is `SIE` might be forced by the Application and with it claiming all HID devices' communication when its window is active (could be checked in source code). In the logs I see that there are no responses from the device, which might confirm that. I will test it myself by the way of next App release.

**Comment by jonathancross** [comment] 2017-08-23 21:03
Thank you.  Would really like to get this resolved so i don't have to go back to YubiKey  :-)

**Comment by szszszsz** [comment] 2017-09-21 08:22
Please retest with latest version: [v1.2-beta.2](https://github.com/Nitrokey/nitrokey-app/releases/tag/v1.2-beta.2).

**Comment by szszszsz** [comment] 2017-09-21 11:48
I have not encountered this issue during retest with `v1.2-beta.2` on MacOS Sierra 10.12.6. 
I had trouble to reproduce it too on this OS. Log suggests this issue could be fixed with latest Nitrokey App version.
Tested both with KeepassX and KeepassXC.

**Comment by jonathancross** [comment] 2017-09-23 01:00
Thanks @szszszsz, unfortunatly I still get the same behavior listed above in original bug report.
Note: I'm on _OS X El Capitan_ `10.11.6 (15G1611)`.

LOG:
[nitrokey-v1.2-log2.txt](https://github.com/Nitrokey/nitrokey-app/files/1326166/nitrokey-v1.2-log2.txt)
 
Segfault (stdout):

    Qt has caught an exception thrown from an event handler. Throwing
    exceptions from an event handler is not supported in Qt.
    You must not let any exception whatsoever propagate through Qt code.
    If that is not possible, in Qt 5 you must at least reimplement
    QCoreApplication::notify() and catch all exceptions there.

    2017-09-23 02:56:40.755 nitrokey-app[3991:153735] -[_CFXNotificationNameRegistration count]: unrecognized selector sent to instance 0x7fb89b3f1850
    2017-09-23 02:56:40.755 nitrokey-app[3991:153735] An uncaught exception was raised
    2017-09-23 02:56:40.755 nitrokey-app[3991:153735] -[_CFXNotificationNameRegistration count]: unrecognized selector sent to instance 0x7fb89b3f1850
    2017-09-23 02:56:40.804 nitrokey-app[3991:153735] (
      0   CoreFoundation                      0x00007fff8c841452 __exceptionPreprocess + 178
      1   libobjc.A.dylib                     0x00007fff91dbaf7e objc_exception_throw + 48
      2   CoreFoundation                      0x00007fff8c8ab18d -[NSObject(NSObject) doesNotRecognizeSelector:] + 205
      3   CoreFoundation                      0x00007fff8c7b14c1 ___forwarding___ + 1009
      4   CoreFoundation                      0x00007fff8c7b1048 _CF_forwarding_prep_0 + 120
      5   HIToolbox                           0x00007fff91b26e3d _ZL9EnsureMTDP14MenuSelectDataP8MenuDatah + 42
      6   HIToolbox                           0x00007fff91c6046f _ZL31UpdateOpenMenuAndChildrenBoundsP8MenuDataP5Pointh + 66
      7   HIToolbox                           0x00007fff91c60424 _ResizeOpenMenu + 26
      8   HIToolbox                           0x00007fff91b3d89e _ZL19RecalcAndResizeMenuP13OpaqueMenuRef + 110
      9   HIToolbox                           0x00007fff91b3a900 _ZL17MenuWindowHandlerP25OpaqueEventHandlerCallRefP14OpaqueEventRefPv + 305
      10  HIToolbox                           0x00007fff91abc7be _ZL23DispatchEventToHandlersP14EventTargetRecP14OpaqueEventRefP14HandlerCallRec + 1231
      11  HIToolbox                           0x00007fff91abbc48 _ZL30SendEventToEventTargetInternalP14OpaqueEventRefP20OpaqueEventTargetRefP14HandlerCallRec + 404
      12  HIToolbox                           0x00007fff91abbaab SendEventToEventTargetWithOptions + 43
      13  HIToolbox                           0x00007fff91aedc2d _ZL17FlushWindowObjectP10WindowDataPPvh + 482
      14  HIToolbox                           0x00007fff91aed71d _ZL15FlushAllBuffersP19__CFRunLoopObservermPv + 229
      15  CoreFoundation                      0x00007fff8c7d5fc7 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 23
      16  CoreFoundation                      0x00007fff8c7d5f37 __CFRunLoopDoObservers + 391
      17  CoreFoundation                      0x00007fff8c7b4e0f CFRunLoopRunSpecific + 271
      18  HIToolbox                           0x00007fff91ae4935 RunCurrentEventLoopInMode + 235
      19  HIToolbox                           0x00007fff91ae4677 ReceiveNextEventCommon + 184
      20  HIToolbox                           0x00007fff91ae45af _BlockUntilNextEventMatchingListInModeWithFilter + 71
      21  AppKit                              0x00007fff90722df6 _DPSNextEvent + 1067
      22  AppKit                              0x00007fff90722226 -[NSApplication _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 454
      23  AppKit                              0x00007fff90991a82 -[NSApplication _doModalLoop:peek:] + 653
      24  AppKit                              0x00007fff90b73530 __33-[NSApplication runModalSession:]_block_invoke + 80
      25  AppKit                              0x00007fff90b733f0 -[NSApplication runModalSession:] + 148
      26  libqcocoa.dylib                     0x000000011113ad0a qt_plugin_instance + 130170
      27  QtCore                              0x000000010e90afa1 _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE + 401
      28  QtWidgets                           0x000000010deb81e9 _ZN7QDialog4execEv + 377
      29  nitrokey-app                        0x000000010daa4201 _ZN13AppMessageBox10warningBoxE7QString + 225
      30  nitrokey-app                        0x000000010da2d3d2 main + 4306
      31  libdyld.dylib                       0x00007fff9c5c05ad start + 1
    )
    Segmentation fault: 11

**Comment by szszszsz** [comment] 2017-09-25 09:51
I have looked at the log and seen communication with the device was cut for a brief moment (about 13 seconds) which confused the Application. I cannot avoid the communication loss. Perhaps running the App with root privileges will change this.
I am afraid I cannot help in other way in your use case than to suggest not using both applications at the same time and encourage you to upgrade to Sierra 10.12.6, where it is handled as desired.
I am closing this as `wontfix` due to cause being out of the Application scope (invalid communication handling on OS side) and because of not supporting MacOS Yosemite 10.11 directly.

**Closed by szszszsz** 2017-09-25 09:51 UTC
Labels: bug, in progress, wontfix
