### ISSUE TITLE
Storing HOTP or TOTP is not working on Win10

### ISSUE THREAD

**Issue by Belatronix** [Nitrokey/nitrokey-app#222] opened 2017-02-02 14:52 UTC
Nitrokey Storage Firmware 0.44
Nitrokey App 0.6.2

Error Message:   Error writing configuration!

**Comment by szszszsz** [comment] 2017-02-03 10:14
Hi! We have just made available Nitrokey App v0.6.3 on our [download](https://www.nitrokey.com/download) page. Please update the App and reopen the issue if it would still occur.

**Comment by szszszsz** [comment] 2017-02-03 10:15
[ closing as a duplicate of #214 ]

**Closed by szszszsz** 2017-02-03 10:15 UTC
Labels: prio:high
