### ISSUE TITLE
“Nitrokey App v1.1” is damaged - Improperly signed/built

### ISSUE THREAD

**Issue by stgarf** [Nitrokey/nitrokey-app#255] opened 2017-06-12 06:34 UTC
<img width="801" alt="screen shot 2017-06-11 at 11 33 48 pm" src="https://user-images.githubusercontent.com/1694002/27021607-76bd6dc8-4efe-11e7-8d33-ea878d1de7f3.png">

**Comment by szszszsz** [comment] 2017-06-20 09:10
Hi @stgarf !
Thank you for reporting. Unfortunately this issue has not been resolved yet. Please use the code-unsigned (but with sha and gpg) package until then. If you have further questions please write at #246.
Closing as a duplicate of #246.

**Closed by szszszsz** 2017-06-20 09:10 UTC
